/etc/letsencrypt/archive/gitarhefte.no/FROM node:latest as build
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
COPY package.json /usr/src/app

RUN npm install --no-optional
RUN npm audit fix

COPY . /usr/src/app
RUN npm run build

FROM nginx:alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
COPY /etc/letsencrypt/archive/gitarhefte.no/fullchain2.pem /etc/nginx
COPY privkey.pem /etc/nginx

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
